### PR TITLE
Renamed a few things.

### PR DESCRIPTION
**Pull request by UserName504**

### CODE REVIEW

**Review by a96lex — CHANGES_REQUESTED** [review]
Great, this is better :)
Can you add an usage example to readme.md? @UserName504

**Comment by a96lex** [comment]
> Great, this is better :)
> Can you add an usage example to readme.md? @UserName504

https://github.com/aflorithmic/aflr_python/blob/class-methods/README.md#script You can have it after .list() method. Explain how the user should call this method and how can it be used to crate a script

**Review by FeaR6077 — APPROVED** [review]
LGTM

**Review by tonythree — APPROVED** [review]
lgtm

**Pull request merged**
